
const Constants = {
  ADMIN_ID: 1,
  ALUNO_ID: 5,
  INSTRUTOR_ID: 2,
  GERENCIA_ID: 3,
  LIMPEZA_ID: 4,
  VISITANTE_ID: 6,
  SEGURANCA_ID: 7,
  RECEPCAO_ID: 10,
  phoneMask: {
    mask: [
      '(',
      /\d/,
      /\d/,
      ')',
      ' ',
      /\d/,
      ' ',
      /\d/,
      /\d/,
      /\d/,
      /\d/,
      '-',
      /\d/,
      /\d/,
      /\d/,
      /\d/,
    ],
  },
  cpfMask: {
    mask: [
      /\d/,
      /\d/,
      /\d/,
      '.',
      /\d/,
      /\d/,
      /\d/,
      '.',
      /\d/,
      /\d/,
      /\d/,
      '-',
      /\d/,
      /\d/,
    ],
  },
  alturaMask: {
    mask: [/\d/, '.', /\d/, /\d/],
  },
  pesoMask: {
    mask: [/\d/, /\d/, '.', /\d/, /\d/],
  },

  cnpjMask: {
    // 99.999.999/9999-99
    mask: [
      /\d/,
      /\d/,
      '.',
      /\d/,
      /\d/,
      /\d/,
      '.',
      /\d/,
      /\d/,
      /\d/,
      '/',
      /\d/,
      /\d/,
      /\d/,
      /\d/,
      '-',
      /\d/,
      /\d/,
    ],
  },

  meses: [
    { value: 1, label: 'Janeiro' },
    { value: 2, label: 'Fevereiro' },
    { value: 3, label: 'Março' },
    { value: 4, label: 'Abril' },
    { value: 5, label: 'Maio' },
    { value: 6, label: 'Junho' },
    { value: 7, label: 'Julho' },
    { value: 8, label: 'Agosto' },
    { value: 9, label: 'Setembro' },
    { value: 10, label: 'Outubro' },
    { value: 11, label: 'Novembro' },
    { value: 12, label: 'Dezembro' },
  ],

  // TIPOS DE TRANSACAO
  TR_TIPO_RECEITA: 1,
  TR_TIPO_DESPESA: 2,

  // CATEGORIAS DE TRANSACAO
  TR_CATEGORIA_MENSALIDADE: 1,
  TR_CATEGORIA_DIARIA: 2,
  TR_CATEGORIA_AULAPARTICULAR: 3,
  TR_CATEGORIA_VENDA_PRODUTO: 4,
  TR_CATEGORIA_DESPESA_FIXA: 5,
  TR_CATEGORIA_DESPESA_VARIAVEL: 7,
  TR_CATEGORIA_DESPESA_REPAROS: 8,
  TR_CATEGORIA_DESPESA_SALARIO: 9,
  TR_CATEGORIA_DESPESA_AQUISICAO: 10,
  TR_CATEGORIA_DESPESA_COMBUSTIVEL: 11,
  TR_CATEGORIA_OUTRASRECEITAS: 12,
  TR_CATEGORIA_OUTRASDESPESAS: 13,
};

export default Constants;
